version: '3'
services:
  db:
    container_name: app-db
    image: postgres:15
    restart: always
    ports: 
      - "15432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
